//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LecturasNotificaciones
    {
        public int IdLectura { get; set; }
        public Nullable<int> IdNotificacion { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaLectura { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Notificaciones Notificaciones { get; set; }
    }
}
