//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PadelAppEntities : DbContext
    {
        public PadelAppEntities()
            : base("name=PadelAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Canchas> Canchas { get; set; }
        public virtual DbSet<CanchasReservadas> CanchasReservadas { get; set; }
        public virtual DbSet<Horarios> Horarios { get; set; }
        public virtual DbSet<PartidosCreadosUsuarios> PartidosCreadosUsuarios { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<PrecioCancha> PrecioCancha { get; set; }
        public virtual DbSet<RecaudacionCancha> RecaudacionCancha { get; set; }
        public virtual DbSet<Parejas> Parejas { get; set; }
        public virtual DbSet<PartidoResultado> PartidoResultado { get; set; }
        public virtual DbSet<LecturasNotificaciones> LecturasNotificaciones { get; set; }
        public virtual DbSet<Notificaciones> Notificaciones { get; set; }
    }
}
