//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parejas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parejas()
        {
            this.PartidoResultado = new HashSet<PartidoResultado>();
        }
    
        public int IdPareja { get; set; }
        public Nullable<int> IdJugador1 { get; set; }
        public Nullable<int> IdJugador2 { get; set; }
        public Nullable<int> IdJugador3 { get; set; }
        public Nullable<int> IdJugador4 { get; set; }
        public string UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> IdPartido { get; set; }
    
        public virtual Perfil Perfil { get; set; }
        public virtual Perfil Perfil1 { get; set; }
        public virtual Perfil Perfil2 { get; set; }
        public virtual Perfil Perfil3 { get; set; }
        public virtual PartidosCreadosUsuarios PartidosCreadosUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartidoResultado> PartidoResultado { get; set; }
    }
}
