//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartidoResultado
    {
        public int IdPartido { get; set; }
        public Nullable<int> IdCanchaReservada { get; set; }
        public Nullable<int> IdPareja1 { get; set; }
        public Nullable<int> IdPareja2 { get; set; }
        public Nullable<int> Set1Pareja1 { get; set; }
        public Nullable<int> Set1Pareja2 { get; set; }
        public Nullable<int> Set2Pareja1 { get; set; }
        public Nullable<int> Set2Pareja2 { get; set; }
        public Nullable<int> Set3Pareja1 { get; set; }
        public Nullable<int> Set3Pareja2 { get; set; }
        public string UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual CanchasReservadas CanchasReservadas { get; set; }
        public virtual Parejas Parejas { get; set; }
        public virtual Parejas Parejas1 { get; set; }
    }
}
