//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartidosCreadosUsuarios
    {
        public int Id { get; set; }
        public Nullable<int> IdCanchaReservada { get; set; }
        public Nullable<int> IdJugador1 { get; set; }
        public Nullable<int> IdJugador2 { get; set; }
        public Nullable<int> IdJugador3 { get; set; }
        public Nullable<int> IdJugador4 { get; set; }
    
        public virtual CanchasReservadas CanchasReservadas { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual Usuario Usuario3 { get; set; }
    }
}
