//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecaudacionCancha
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaRecaudacion { get; set; }
        public Nullable<int> CanchaReservadaId { get; set; }
        public Nullable<decimal> MontoCancha { get; set; }
        public Nullable<decimal> MontoAdicional { get; set; }
        public Nullable<decimal> MontoFinal { get; set; }
    
        public virtual CanchasReservadas CanchasReservadas { get; set; }
    }
}
